### ISSUE TITLE
log这个功能完全非必要的配置

### ISSUE THREAD

**Issue by go-bi** [slince/spike-go#1]
log功能可以为附加，完全非必要强制的。越简单越好，现在是强制输出打印一些没用的信息(非必要的)

**Comment by slince** [comment]
@go-bi  日志功能缺失是非必要的，基于配置文件里将 `console` 设置为 `false` ； file 值设置为空 就不会打日志了；或者直接将日志等级提到error；默认等级是trace  最基本的日志
